export const Questions = [
    '1. Eu gosto de me expressar através de meios artísticos.',
    '2. Eu normalmente prefiro trabalhar sozinho.',
    '3. Eu tenho facilidade para convencer as pessoas das minhas ideias.',
    '4. Normalmente as pessoas me veem como um líder.',
    '5. Eu gosto de resolver desafios complexos.',
    '6. Eu sempre sou o amigo que motiva os outros.',
    '7. Eu me preocupo que tudo saia como o planejado.',
    '8. Eu costumo de me engajar em projetos sociais.',
    '9. Eu gosto de tarefas que exigem precisão e atenção aos detalhes.',
    '10. Eu gosto de entender como as coisas funcionam.',
    '11. Eu me sinto bem auxiliando as pessoas na resolução dos seus problemas.',
    '12. Eu dedico parte do meu tempo para aprimorar minhas habilidades técnicas.',
    '13. As pessoas normalmente me procuram para desabafar sobre seus sentimentos.',
    '14. Eu tendo a agir com a razão e não com a emoção.',
    '15. Eu gosto de planejar minhas atividades com antecedência.',
    '16. Normalmente eu escolho caminhos não convencionais para a resolução de problemas.',
    '17. Eu gosto de tarefas que me permitam ter autonomia.',
    '18. Eu me sinto bem em ambientes com regras bem definidas.',
    '19. Eu gosto de escrever ou falar sobre meus sentimentos.',
    '20. Eu normalmente me ofereço para participar de programas de monitoria na escola/faculdade.',
    '21. Nos meus trabalhos escolares normalmente eu assumo a posição de liderança.',
    '22. Eu costumo tomar decisões lógicas.',
    '23. Eu costumo fazer desenhos no caderno durante a aula.',
    '24. As pessoas normalmente me ouvem.',
    '25. Minha parte preferida dos trabalhos escolares era ajudar na confecção dos cartazes/apresentações de slides.',
    '26. Eu gosto de trabalhos manuais.',
    '27. Eu participei/participo de entidades estudantis (grêmios/centros acadêmicos).',
    '28. Quando eu gosto de um assunto eu procuro entendê-lo com profundidade.',
    '29. As pessoas me consideram uma pessoa criativa.',
    '30. As pessoas me consideram tímido/introspectivo.'
];
